version: '3.8'

services:
  db:
    image: postgres:15
    container_name: blogapi-db
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: 87115
      POSTGRES_DB: blog_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .       # path to FastAPI Dockerfile
    container_name: blogapi-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://blog_user:87115@db:5432/blog_api_db
    volumes:
      - .:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./app/front
    container_name: blogapi-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"   # React dev server runs on 3000
    volumes:
      - ./app/front:/usr/src/app:cached 
      - /usr/src/app/node_modules       

    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
      - WDS_SOCKET_PORT=3000
    command: npm start


volumes:
  postgres_data:
